apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkuscoffeeshop-web
spec:
  template:
    spec:
      containers:
        - name: quarkuscoffeeshop-web
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: cafe-cluster-kafka-bootstrap:9092
            - name: REST_URL
              value: http://quarkuscoffeeshop-web-quarkuscoffeeshop-demo.apps.cluster-prgx-7369.prgx-7369.example.opentlc.com
            - name: STREAM_URL
              value:  http://quarkuscoffeeshop-web-quarkuscoffeeshop-demo.apps.cluster-prgx-7369.prgx-7369.example.opentlc.com/dashboard/stream
            - name: CORS_ORIGINS
              value: http://quarkuscoffeeshop-demo.apps.cluster-prgx-7369.prgx-7369.example.opentlc.com
            - name: STORE_ID
              value: RALEIGH

