apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quarkuscoffeeshop-web
  namespace: quarkuscoffeeshop-demo
spec:
  host: quarkuscoffeeshop-web-quarkuscoffeeshop-demo.apps.cluster-atlanta-91a7.atlanta-91a7.example.opentlc.com
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: quarkuscoffeeshop-web
    weight: 100
  wildcardPolicy: None