apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkuscoffeeshop-customermocker
spec:
  template:
    spec:
      containers:
        - name: quarkuscoffeeshop-customermocker
          env:
            - name: REST_URL
              value: http://quarkuscoffeeshop-web-quarkuscoffeeshop-demo.apps.cluster-5fb9.5fb9.example.opentlc.com
